
# Usa una imagen base de Java
FROM openjdk:17

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia el archivo JAR de tu aplicación Spring Boot al contenedor
COPY target/scooterService-0.0.1-SNAPSHOT.jar /app/app.jar

# Expone el puerto en el que se ejecutará tu aplicación (si es necesario)
EXPOSE 8083

# Comando para ejecutar tu aplicación al iniciar el contenedor
CMD ["java", "-jar", "app.jar"]

LABEL authors="lulo"

